singnet/das-serverless-functions

das-query-engine/action_mapper.py
das-query-engine/actions.py
das-query-engine/validators/actions.py

[#39] add get_incoming_links

---

.github/workflows/vultr-build.yml
scripts/run-tests.sh

ci: testing source code

---

.github/workflows/vultr-build.yml

* Add the changelog manually (this will be used in the message sent to the mattermost)

ci: manual changelog

---

.github/workflows/vultr-build.yml

[das-query-engine#127][das-query-engine#128] Fix mattermost message

---

.github/workflows/vultr-build.yml

Fix prefix v to image tag

---

scripts/run-tests.sh

[#78] Display logs and exit the container upon encountering an error.

---

das-query-engine/actions.py
das-query-engine/validators/actions.py

Resolves singnet/das-query-engine#173

[das-query-engine#173] Change the type hint in query()

---

das-query-engine/action_mapper.py
das-query-engine/actions.py
das-query-engine/exceptions.py
das-query-engine/handler.py
das-query-engine/tests/integration/handle/base_test_action.py
das-query-engine/tests/integration/handle/test_handshake_action.py
das-query-engine/tests/unit/test_action_mapper.py
das-query-engine/tests/unit/test_decorators.py
das-query-engine/tests/unit/test_version.py
das-query-engine/utils/decorators.py
das-query-engine/utils/version.py
das-query-engine/validators/actions.py

Closes singnet/das-query-engine#159

[das-query-engine#159] Validate library version when connecting to Function

---

das-query-engine/action_mapper.py
das-query-engine/actions.py
das-query-engine/validators/actions.py

[#88] Add create_field_index() method

---

.github/workflows/vultr-build.yml

[das-toolbox#44] Push a function latest tag to Docker Hub

---

CHANGELOG
Makefile
das-query-engine/handler.py
das-query-engine/tests/integration/handle/base_test_action.py

[#90] Fix serializing/deserializing query answers

---

CHANGELOG
das-query-engine/action_mapper.py
das-query-engine/actions.py
das-query-engine/validators/actions.py

[#97] Add custom_query() and update create_field_index()

---

CHANGELOG
Makefile
das-query-engine/action_mapper.py
das-query-engine/actions.py
das-query-engine/tests/unit/test_action_mapper.py
das-query-engine/validators/actions.py

[#100] Add fetch(). New Action

---

das-query-engine/actions.py
das-query-engine/validators/actions.py

Resolves singnet/das-query-engine#214

[das-query-engine#214] Improve query parameter in fetch()

---

CHANGELOG
das-query-engine/action_mapper.py
das-query-engine/actions.py
das-query-engine/validators/actions.py

Resolves #113 
Also related to https://github.com/singnet/das-query-engine/issues/108

[#113] Add create_context command in query-engine function

---

.github/workflows/vultr-build.yml

Closes https://github.com/singnet/das/issues/6

[das#6] Migrate contents of das-scripts-pipeline to das

---

das-query-engine/action_mapper.py
das-query-engine/actions.py
das-query-engine/tests/unit/test_action_mapper.py
das-query-engine/validators/actions.py

Resolves singnet/das-query-engine#114

[das-query-engine#114] Add kwarg to commit_changes()

---

.github/workflows/testing.yml
.github/workflows/vultr-build.yml
Makefile
das-query-engine/handler.py
das-query-engine/tests/integration/handle/test_query_action.py
das-query-engine/tests/unit/test_handler.py
scripts/run-tests.sh

[#109] Fix test_query_action

---

das-query-engine/action_mapper.py
das-query-engine/validators/actions.py

Closes https://github.com/singnet/das-query-engine/issues/219

[das-query-engine#219] Weird response to malformed DAS query

---

Makefile
das-query-engine/actions.py
das-query-engine/validators/actions.py

Related singnet/das-query-engine#256

[das-query-engine#256] Bug Fix

---

.github/workflows/vultr-build.yml

Closes https://github.com/singnet/das/issues/22

[das#22] Add title and deliverable message to versioning job

---

.github/workflows/testing.yml

Closes https://github.com/singnet/das/issues/52

[das#52] Run periodic checks in the 3 main repos and report problems in a specific Mattermost channel

---

das-query-engine/action_mapper.py
das-query-engine/actions.py
das-query-engine/exceptions.py
das-query-engine/tests/unit/test_action_mapper.py
das-query-engine/validators/actions.py
requirements.txt

[#123] Support AtomDB new indexes

---

das-query-engine/actions.py
das-query-engine/validators/actions.py

Fixed optional fields, fixed create index

[HOTFIX ] Fix create_field_index and optinal fields

---

.github/workflows/testing.yml
.github/workflows/vultr-build.yml
requirements.txt

Closes https://github.com/singnet/das/issues/56

[#56] Review release process

---

das-query-engine/action_mapper.py
das-query-engine/actions.py
das-query-engine/tests/integration/handle/test_count_atoms_action.py
das-query-engine/tests/unit/test_action_mapper.py
das-query-engine/validators/actions.py

Added support to new parameters in count_atoms.

[das#226] Changed count_atoms validator

---

.github/workflows/testing.yml
.github/workflows/vultr-build.yml
requirements.txt

Closes https://github.com/singnet/das/issues/59

[#59] Separate Tests and Lint into Individual jobs on pipeline

---

.github/workflows/vultr-build.yml

Closes https://github.com/singnet/das-toolbox/issues/101

[#101] "das-cli faas update version" is not getting latest version

---

das-query-engine/tests/integration/handle/test_get_incoming_links.py

Closes https://github.com/singnet/das/issues/83

[das#83] fixing test

---

.black.cfg
.flake8.cfg
.github/workflows/testing.yml
.isort.cfg
Makefile

Closes https://github.com/singnet/das/issues/75

[das#75] Make sure all repos are using the same lint config

---

.github/workflows/testing.yml

[#142]: Add das-cli to load the database instead of docker-compose

---

.github/workflows/testing.yml

Reverts singnet/das-serverless-functions#152

Revert "[#142]: Add das-cli to load the database instead of docker-compose"

---

das-query-engine/tests/integration/handle/test_get_atom_action.py
das-query-engine/tests/integration/handle/test_get_incoming_links.py
das-query-engine/tests/integration/handle/test_get_link_action.py
das-query-engine/tests/integration/handle/test_get_links_action.py
das-query-engine/tests/integration/handle/test_get_node_action.py
das-query-engine/tests/integration/handle/test_query_action.py

[#160] syncing tests with the new Atom DB
